name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version}}
      - name: install modules
        run: yarn install
      - name: test project
        run: yarn test
      - name: build project
        run: yarn build
